Homework1
made-mlops-2022/ilya_popov pull request #1
Opened 2022-11-05 15:28 UTC by ilya0100

# TECHNOPARK, ML-21, Попов Илья
1. В домашнем задании я сделал пайплайны для обучения модели и предсказания, перед этим сделав ноутбук с минимальным решением. Загрузку датасета я осуществил через Google Drive API. Для тестов использовался unittest.
2. EDA: в папке notebooks лежит ноутбук с прототипом пайплайна.
3. Для тренировки написана отдельная функция, вызов описан в readme
4. Для предсказания аналогично.
5. Проект разбит на модули, и каждая функция выполняет отдельное действие.
6. Логгеры используются в функциях обучения и предсказанияю
7. Написаны тесты на отдельные функции и на прогон тренировки и тестирования.
8. Для тестов я вырезал небольшую часть датасета.
9.  Есть конфигурации с разными моделями и разной предобработкой.
10. Для всех сущностей в конфиге используются датаклассы.
11.  Трансформер заполняет пропуски и нормализует данные.
12. Зависимости находятся в файле requirements.txt.
13. В CI запускается проверка кода с помощью flake8 и тесты.
Неполностью я сделал пункт с генерацией данных для тестов и не добавил в проект mlflow, dvc и hydra, а остальные пункты я вроде сделал полностью. Данные для тестов наверное можно засчитать как датасет для контроля версий. И еще функции обучения и предсказания выделены в entrypoints.

2022-11-12 21:26 UTC, nickdndev requested changes

2022-11-12 21:26 UTC, nickdndev commented on ml_project/data/make_dataset.py
> +    path: str, file_id: str, service: Resource, logger: Logger
don't send logger as input for method 
create in file

2022-11-12 21:26 UTC, nickdndev commented on ml_project/enities/feature_params.py
> +    features_to_drop: Optional[List[str]]
Optional + list is useless 
for this case please use empty list instead none

2022-11-12 21:26 UTC, nickdndev commented on ml_project/enities/feature_params.py
> +    features_to_drop: Optional[List[str]]
features_to_drop: List[str]

2022-11-12 21:26 UTC, nickdndev commented on ml_project/models/models_fit_predict.py
> +        case "LogisticRegression":
set default case and raise error 

case _:
   raise...

2022-11-12 21:26 UTC, nickdndev commented on tests/test_end2end.py
> +class TestEnd2End(unittest.TestCase):
rename to TestFitPredictPipeline

2022-11-19 19:28 UTC, nickdndev commented
необходимо провести самооценку по каждому пункту

2022-11-22 05:51 UTC, ilya0100 commented
### Самооценка:
1. В пулл-реквесте проведена самооценка - 1 балл
2. Выполнено EDA - 1 балл
3. Написана функция/класс для тренировки модели, вызов оформлен как утилита командной строки, записана в readme инструкцию по запуску - 3 балла
4. Написана функция/класс predict (вызов оформлен как утилита командной строки), которая примет на вход артефакт/ы от обучения, тестовую выборку (без меток) и запишет предикт по заданному пути, инструкция по вызову записана в readme - 3 балла
5. Проект имеет модульную структуру - 2 балла
6. Использованы логгеры - 2 балла
7. Написаны тесты на отдельные модули и на прогон обучения и predict - 3 балла
8. Для тестов генерируются синтетические данные, приближенные к реальным - 1 балл (т. к. я использовал часть датасета а не сгенерированные данные)
9. Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель - 3 балла
10. Используются датаклассы для сущностей из конфига, а не голые dict - 2 балла
11. Напишите кастомный трансформер и протестируйте его - 3 балла
12. В проекте зафиксированы все зависимости - 1 балл
13. Настроен CI для прогона тестов, линтера на основе github actions - 3 балла

#### Дополнительные баллы:
- выделите в своем проекте несколько entrypoints в виде консольных утилит - 1 балл
- добавьте датасет под контроль версий - 1 балл

2022-11-25 15:52 UTC, nickdndev approved these changes

2022-11-26 05:17 UTC, merged